CREATE USER docker WITH ENCRYPTED PASSWORD 'docker';
GRANT ALL PRIVILEGES ON DATABASE nest TO docker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO docker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO docker;