-- INSERT INTO nest_user (name) VALUES 
--     ('Group 1'),
--     ('Group 2'),
--     ('All Users'),
-- ;
-- INSERT INTO nest_user (name, parent_id) VALUES 
--     ('Alex', 1),
--     ('Alex', 3),
--     ('Caleb', 2),
--     ('Caleb', 3),
--     ('Random User 3', 1),
--     ('Random User 3', 2),
--     ('Random User 3', 3),
-- ;